### ISSUE TITLE
Add Weinberg operator

### ISSUE THREAD

**Issue by DavidMStraub** [DsixTools/python-smeftrunner#2]
Comment by @celis:

> On the latest version of DsixTools we have added the dimension five Weinberg operator and its running to the code.  This is useful because it then gives the neutrino masses and the rotation by the PMNS matrix when going to the fermion mass basis, which affects indirectly the physics of the dimension six operators.   

> In the DsixTools output this operator is appearing as the last Block of WCs (Block WCLLPHIPHI).  The manual on the website https://dsixtools.github.io has been updated with this operator, collecting the beta function adapted to our conventions (like in Warsaw paper) and the reference where its taken from.

**Comment by DavidMStraub** [comment]
Yes, this should be added.

**Comment by celis** [comment]
Ok!

**Comment by DavidMStraub** [comment]
Added by @pxylisa in a9037cb5c051087effb208c468ea24c09910f601.

Tests still need to be fixed (issue #8).
