### ISSUE TITLE
remove print

### ISSUE THREAD

**Issue by DavidMStraub** [DsixTools/python-smeftrunner#3]
@celis:

> when running smeft.dump a number is printed on screen

**Comment by DavidMStraub** [comment]
I can't reproduce that. Can you give an example please?

**Comment by avelino3000** [comment]
Just following the steps given in your README one gets a number after executing the python command smeft.dump(C_out, open('my_output_file.dat', 'w'))

**Comment by DavidMStraub** [comment]
Oh, now I get it. `pylha.dump` returns the number of bytes. This should be fixed there. Thanks
