### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by DavidMStraub** [DsixTools/python-smeftrunner#4]
@celis:

> in setup.py, maybe it is good to add numpy to the list of packages:    "install_requires=['scipy', 'pylha', 'pyyaml’]”

**Comment by DavidMStraub** [comment]
Right. I somehow assumed it's enough that scipy depends on numpy, but it [may not be](https://github.com/scipy/scipy/blob/master/setup.py#L352-L365). Anyway I think the most important thing to add is a comment in the README that scipy & numpy should be installed *beforehand* (with pip, it usually fails).

**Comment by celis** [comment]
Ok!
