### ISSUE TITLE
Tests fail after addition of Weinberg operator

### ISSUE THREAD

**Issue by DavidMStraub** [DsixTools/python-smeftrunner#8]

**Comment by Demerzelx** [comment]
solved.

**Comment by DavidMStraub** [comment]
@pxylisa unfortunately there is still an error. If you go to the [list of commits](https://github.com/DsixTools/python-smeftrunner/commits/master) and click on the red "x" next to the commit message, you can check the error message. It reads:

```python
File "smeftrunner/tests/test.py", line 35, in <module>
    C[n] = np.array(rC[1][i])
```

**Comment by Demerzelx** [comment]
so... solved. 

https://travis-ci.org/DsixTools/python-smeftrunner/builds/274633386

**Comment by DavidMStraub** [comment]
Great!
