### ISSUE TITLE
flavor indices in WCQQ3

### ISSUE THREAD

**Issue by celis** [DsixTools/python-smeftrunner#9]
Hi, checking the outputs of both codes I find a difference ordering of the flavour indices in the BLOCK WCQQ3
for example:
    3    2    1    3    -0.0005388147142823533
    3    3    1    3    0.011235333189774092

appear in DsixTools as 

1 3 3 2 -0.000539	# qq3(1,3,3,2)
1 3 3 3 0.011235	# qq3(1,3,3,3)

so from the numerical agreement it seems just a reordering of the indices.  abcd -> cdab.  Was it deliberate or was a bug?  

Regards

**Comment by DavidMStraub** [comment]
Well, qq3 is symmetric under `ijkl` -> `klij`, right? So it depends on how one deals with this symmetry. In DsixTools as far as I understand you omit one of the cases (such that the output does not contain redundancies), right?

In python-smeftrunner as of know, all WCs are just dumb tensors that don't know about their symmetries. That is, the output should contain both `3 2 1 3` and `1 3 3 2`, for instance, with the same value. Can you confirm that?

**Comment by celis** [comment]
"Well, qq3 is symmetric under ijkl -> klij, right?"

right

" So it depends on how one deals with this symmetry. In DsixTools as far as I understand you omit one of the cases (such that the output does not contain redundancies), right?"  

 yes, following the categories of table 6 & 7 of the manual (arxiv version), all redundancies are eliminated and only a given set of independent entries are given in the output. 
 
For the input card it works similarly, only giving a set of independent coefficients and then internally the code takes care of filling the entries of the dependent coefficients according to the symmetry properties of the operators.      

"In python-smeftrunner as of now, all WCs are just dumb tensors that don't know about their symmetries. That is, the output should contain both 3 2 1 3 and 1 3 3 2, for instance, with the same value. Can you confirm that?"


right, I just checked in BLOCK WCQQ3 and indeed is as you comment.  

thanks for the clarifications.

**Comment by DavidMStraub** [comment]
Oh, good point about the input file, because reconstructing the "full" tensor from the relevant entries using the symmetry relations is currently not done as far as I remember. This might well be the reason for the factor of 2 missing in issue #1 ...

**Comment by celis** [comment]
Yes, I was suspecting this.  For example using the default input card WCsInput-CPV-SMEFT.dat from https://dsixtools.github.io, I get in Mathematica

Block WC2
1 0.002584	# phi

while the python code returns 

BLOCK WC2
 1    0.00129182564865

The Mathematica result is ~2 times the python one.  The same happens for other entries, like the phiBox coefficient.

Looking at the analytical expression for the RGE and the non-vanishing inputs. I think in this case the factor of 2 is due to the input

Block WCPHIQ3
1 3 1.0		# phiq3(1,3)

which is associated to a Hermitian matrix in flavor space.     When reconstructing the 3 1 entry from the 1 3 then might give the missing 2.   

In our Mathematica code reconstructing the missing entries from the input card using the symmetries of the operators is done in input.m (coded by Avelino). 

Regards

**Comment by DavidMStraub** [comment]
Fixed. Implemented the symmetrization of inputs as well as the omission of redundant entries in the output, with extensive unit tests.
